server:
  port: 8081
  servlet:
    context-path: /Demo6
spring:

  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost/demo?serverTimezone=UTC&useUnicode=true&characterEncoding=UTF-8
    username: root
    password: root
    type: com.alibaba.druid.pool.DruidDataSource
  mvc:
    view:
      prefix: /jsp/
      suffix: .jsp
    pathmatch:
      #设置是否后缀匹配模式，如“/user”是否匹配“/user.*”,默认真即匹配
      #true,那么/user.html,/user.*都可以访问
      use-suffix-pattern: true

mybatis:
  config-location: classpath:SqlMapConfig.xml
#  mapper-locations: classpath:/mapper/*.xml
